version: "3.6"
services:
  haproxy:
    image: xorilog/haprox-consuled
    networks:
      - haprox-demo
    ports:
      - "80:80"
    environment:
      SILO: "b2c"
      CONSUL_URL: "${DEFAULT_IP}:8500"

  whoami-sorry: &whoami
    image: emilevauge/whoami
    hostname: whoami-sorry
    environment:
      CONSUL_URL: ${DEFAULT_IP}
      SERVICE_NAME: "reservation-gateway"
      SILO: ${SILO:-"b2c"}
    networks:
      - haprox-demo
      - consul-demo
  whoami-1:
    <<: *whoami
    hostname: whoami-1
  whoami-2:
    <<: *whoami
    hostname: whoami-2
  whoami-3:
    <<: *whoami
    hostname: whoami-3

networks:
  haprox-demo:
  consul-demo:
    name: cluster_consul_consul-demo
