version: "3.6"
services:
  haproxy:
    image: xorilog/haprox-consuled
    networks:
      - haprox-demo
    volumes:
      - ./conf/dynamic.cfg.ctmpl:/etc/consul/haproxy/dynamic.cfg.ctmpl
      - ./conf/haproxy.cfg:/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      CONSUL_URL: "${DEFAULT_IP}:8500"

  whoami-sorry: &whoami
    image: emilevauge/whoami
    hostname: whoami-sorry
    networks:
      - haprox-demo
    environment:
      CONSUL_URL: "${DEFAULT_IP}:8500"
  whoami-1:
    <<: *whoami
    hostname: whoami-1
  whoami-2:
    <<: *whoami
    hostname: whoami-2
  whoami-3:
    <<: *whoami
    hostname: whoami-3

networks:
  haprox-demo:
