# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/beats/filebeat-oss:7.0.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
# RUN logstash-plugin install logstash-filter-cipher
